/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/clubs/{clubId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 목록 조회
         * @description 동아리의 세션 목록을 페이지네이션으로 조회합니다. status 파라미터로 필터링 가능합니다. (SCHEDULED / ACTIVE / ENDED)
         */
        get: operations["getSessions"];
        put?: never;
        /**
         * 세션 생성
         * @description 동아리 세션을 생성합니다. 반복 옵션 설정 시 요일 기반으로 여러 세션이 일괄 생성됩니다. ADMIN만 가능합니다.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/sessions/{sessionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 세션 시작
         * @description 세션을 시작하고 ACTIVE 상태로 변경합니다. OTP 출석 코드가 발급되며, 동아리 전체 멤버에게 FCM 푸시 알림이 발송됩니다. ADMIN만 가능합니다.
         */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/sessions/{sessionId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 세션 종료
         * @description 세션을 종료하고 ENDED 상태로 변경합니다. 미출석 멤버는 자동으로 ABSENT 처리됩니다. ADMIN만 가능합니다.
         */
        post: operations["endedSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/sessions/{sessionId}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션별 출석 현황 조회
         * @description 세션에 대한 전체 출석 현황을 페이지네이션으로 조회합니다. ADMIN만 가능합니다.
         */
        get: operations["getSessionAttendance"];
        put?: never;
        /**
         * 출석 체크
         * @description OTP 코드를 입력하여 출석을 처리합니다. 세션 시작 후 5분 이내 출석 시 PRESENT, 이후 LATE로 처리됩니다.
         */
        post: operations["checkAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/sessions/{sessionId}/attendance/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 수동 출석 처리
         * @description 관리자가 특정 멤버를 수동으로 출석 처리합니다. ABSENT 상태는 수동 처리할 수 없습니다. ADMIN만 가능합니다.
         */
        post: operations["manualCheckAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/invite-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 유효한 초대코드 조회
         * @description 현재 유효한 초대코드를 조회합니다. ADMIN만 가능합니다.
         */
        get: operations["getCurrentInviteCode"];
        put?: never;
        /**
         * 초대코드 발급
         * @description 동아리 초대코드를 발급합니다. 기존 유효 코드가 있으면 자동으로 무효화 후 새 코드를 발급합니다. ADMIN만 가능합니다.
         */
        post: operations["issueInviteCode"];
        /**
         * 초대코드 무효화
         * @description 현재 유효한 초대코드를 수동으로 무효화합니다. ADMIN만 가능합니다.
         */
        delete: operations["revokeInviteCode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 초대코드로 동아리 가입
         * @description 초대코드를 입력하여 동아리에 가입합니다.
         */
        post: operations["joinClub"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 동아리 생성
         * @description 새로운 동아리를 생성합니다. 생성한 회원은 자동으로 ADMIN 역할을 부여받습니다.
         */
        post: operations["createClub"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 학번, 비밀번호, 학년, 이름으로 신규 회원을 등록합니다.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description Refresh Token으로 새로운 Access Token과 Refresh Token을 재발급합니다.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 로그인된 회원의 Refresh Token을 무효화합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 학번과 비밀번호로 로그인하여 Access Token, Refresh Token을 발급받습니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 로그인한 회원의 프로필 정보를 조회합니다.
         */
        get: operations["getMyInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 내 정보 수정
         * @description 로그인한 회원의 이름 및 푸시 알림 수신 여부를 수정합니다.
         */
        patch: operations["updateMyInfo"];
        trace?: never;
    };
    "/api/v1/members/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 비밀번호 변경
         * @description 현재 비밀번호를 확인 후 새 비밀번호로 변경합니다.
         */
        patch: operations["updateMyPassword"];
        trace?: never;
    };
    "/api/v1/members/me/fcm-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * FCM 토큰 갱신
         * @description 로그인한 회원의 FCM 토큰을 갱신합니다.
         */
        patch: operations["updateFcmToken"];
        trace?: never;
    };
    "/api/v1/clubs/{clubId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 동아리 상세 조회
         * @description 동아리 ID로 동아리 상세 정보를 조회합니다.
         */
        get: operations["getClub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 동아리 정보 수정
         * @description 동아리 이름 또는 설명을 수정합니다. ADMIN만 가능합니다.
         */
        patch: operations["updateClub"];
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 상세 조회
         * @description 세션 ID로 세션 상세 정보를 조회합니다.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /**
         * 세션 삭제 (소프트 삭제)
         * @description 세션을 삭제합니다. 진행 중인(ACTIVE) 세션은 삭제할 수 없습니다. ADMIN만 가능합니다.
         */
        delete: operations["softDeletedSession"];
        options?: never;
        head?: never;
        /**
         * 세션 수정
         * @description 세션 이름, 예정 시작/종료 시간을 수정합니다. 종료된 세션은 수정 불가합니다. ADMIN만 가능합니다.
         */
        patch: operations["updatedSession"];
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/sessions/{sessionId}/attendance/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 출석 상태 변경
         * @description 특정 출석 기록의 상태를 변경합니다. ADMIN만 가능합니다.
         */
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 멤버 역할 변경
         * @description 동아리 멤버의 역할(ADMIN/MEMBER)을 변경합니다. ADMIN만 가능하며, 자기 자신의 역할은 변경할 수 없습니다.
         */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/api/v1/clubs/soft-delete/{clubId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 동아리 삭제 (소프트 삭제)
         * @description 동아리를 삭제 처리합니다. ADMIN만 가능합니다.
         */
        patch: operations["softDeleteClub"];
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/stats/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 출석 트렌드 조회
         * @description 기간별 세션 출석률 추이를 조회합니다. startDate ~ endDate 범위의 세션 데이터를 반환합니다. ADMIN만 가능합니다.
         */
        get: operations["getTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/stats/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멤버별 출석률 조회
         * @description 동아리 전체 멤버의 출석률을 조회합니다. ADMIN만 가능합니다.
         */
        get: operations["getMemberStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/stats/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 출석 상태별 분포 조회
         * @description 기간 내 PRESENT / LATE / ABSENT / ETC 상태별 건수와 비율을 조회합니다. ADMIN만 가능합니다.
         */
        get: operations["getDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 활성 세션 조회
         * @description 현재 진행 중인(ACTIVE) 세션을 조회합니다.
         */
        get: operations["getActiveSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 동아리 멤버 목록 조회
         * @description 동아리 멤버 목록을 조회합니다. 이름 또는 학번으로 검색 가능합니다. ADMIN만 가능합니다.
         */
        get: operations["getClubMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/members/me/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 출석 기록 조회
         * @description 로그인한 회원의 월별 출석 기록과 출석률을 조회합니다. year/month 미입력 시 현재 월 기준으로 조회됩니다.
         */
        get: operations["getMyRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 출석 데이터 내보내기
         * @description 기간 내 출석 데이터를 내보냅니다. memberId 입력 시 특정 멤버만 필터링합니다. ADMIN만 가능합니다.
         */
        get: operations["getExportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clubs/{clubId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 멤버 제명 (소프트 삭제)
         * @description 동아리 멤버를 제명합니다. ADMIN만 가능합니다.
         */
        delete: operations["softdeletedMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionCreateRequestDto: {
            sessionName: string;
            /** Format: date-time */
            expectStartAt: string;
            /** Format: date-time */
            expectEndAt: string;
            isRepeat?: boolean;
            /** @enum {string} */
            dayOfWeek?: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
            /** Format: date */
            repeatEndDate?: string;
        };
        ErrorInfo: {
            code?: string;
            message?: string;
        };
        RsDataVoid: {
            success?: boolean;
            data?: unknown;
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        RsDataSessionStartDto: {
            success?: boolean;
            data?: components["schemas"]["SessionStartDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        SessionStartDto: {
            otpCode?: string;
            uuid?: string;
        };
        RsDataString: {
            success?: boolean;
            data?: string;
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        AttendanceCheckRequestDto: {
            otpCode: string;
        };
        AdminAttendanceRequestDto: {
            /** Format: int64 */
            memberId: number;
            /** @enum {string} */
            attendanceStatus: "PRESENT" | "ABSENT" | "ETC" | "LATE";
            adminNote?: string;
        };
        InviteResponseDto: {
            inviteCode?: string;
        };
        RsDataInviteResponseDto: {
            success?: boolean;
            data?: components["schemas"]["InviteResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        InviteRequestDto: {
            /** Format: int64 */
            clubId?: number;
            inviteCode?: string;
        };
        ClubDto: {
            clubName?: string;
            clubDescription?: string;
        };
        ClubCreateResponseDto: {
            /** Format: int64 */
            clubId?: number;
            fixedUuid?: string;
        };
        RsDataClubCreateResponseDto: {
            success?: boolean;
            data?: components["schemas"]["ClubCreateResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        SignupRequest: {
            stdId: string;
            password: string;
            name: string;
        };
        RsDataSignupResponse: {
            success?: boolean;
            data?: components["schemas"]["SignupResponse"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        SignupResponse: {
            /** Format: int64 */
            id?: number;
            studentId?: string;
            name?: string;
        };
        ReissueTokenRequest: {
            refreshToken: string;
        };
        RsDataTokenResponse: {
            success?: boolean;
            data?: components["schemas"]["TokenResponse"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        LoginRequest: {
            stdId: string;
            password: string;
        };
        MemberProfileUpdateRequest: {
            name: string;
            pushEnabled?: boolean;
        };
        MemberProfileResponse: {
            name?: string;
            clubIds?: number[];
            stdId?: string;
            pushEnabled?: boolean;
        };
        RsDataMemberProfileResponse: {
            success?: boolean;
            data?: components["schemas"]["MemberProfileResponse"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        MemberPaswordUpdateRequest: {
            currentPassword: string;
            newPassword: string;
            confirmNewPassword: string;
        };
        FcmTokenUpdateRequest: {
            fcmToken: string;
        };
        SessionDto: {
            sessionName?: string;
            /** Format: date-time */
            expectStartAt?: string;
            /** Format: date-time */
            expectEndAt?: string;
        };
        AttendanceStatusUpdateDto: {
            /** @enum {string} */
            attendanceStatus: "PRESENT" | "ABSENT" | "ETC" | "LATE";
            adminNote?: string;
        };
        RoleUpdateRequest: {
            /** Format: int64 */
            clubId?: number;
            /** Format: int64 */
            requesterId?: number;
            /** Format: int64 */
            targetMemberId?: number;
            /** @enum {string} */
            newRole?: "ADMIN" | "MEMBER";
        };
        ClubResponseDto: {
            /** Format: int64 */
            id?: number;
            clubName?: string;
            clubDescription?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        RsDataClubResponseDto: {
            success?: boolean;
            data?: components["schemas"]["ClubResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        RsDataTrendResponseDto: {
            success?: boolean;
            data?: components["schemas"]["TrendResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        TrendItem: {
            /** Format: int64 */
            sessionId?: number;
            sessionName?: string;
            /** Format: date */
            date?: string;
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            attended?: number;
            /** Format: double */
            attendanceRate?: number;
        };
        TrendResponseDto: {
            trend?: components["schemas"]["TrendItem"][];
        };
        MemberStatItem: {
            /** Format: int64 */
            memberId?: number;
            name?: string;
            stdId?: string;
            /** Format: int64 */
            totalSessions?: number;
            /** Format: int64 */
            attendedCount?: number;
            /** Format: double */
            attendanceRate?: number;
        };
        MemberStatsResponseDto: {
            members?: components["schemas"]["MemberStatItem"][];
        };
        RsDataMemberStatsResponseDto: {
            success?: boolean;
            data?: components["schemas"]["MemberStatsResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        DistributionResponseDto: {
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            present?: number;
            /** Format: double */
            presentRate?: number;
            /** Format: int64 */
            late?: number;
            /** Format: double */
            lateRate?: number;
            /** Format: int64 */
            absent?: number;
            /** Format: double */
            absentRate?: number;
            /** Format: int64 */
            etc?: number;
            /** Format: double */
            etcRate?: number;
        };
        RsDataDistributionResponseDto: {
            success?: boolean;
            data?: components["schemas"]["DistributionResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageableObject: {
            /** Format: int32 */
            pageNumber?: number;
            unpaged?: boolean;
            paged?: boolean;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
        };
        RsDataSliceSessionResponseDto: {
            success?: boolean;
            data?: components["schemas"]["SliceSessionResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        SessionResponseDto: {
            /** Format: int64 */
            sessionId?: number;
            sessionName?: string;
            /** @enum {string} */
            status?: "SCHEDULED" | "ACTIVE" | "ENDED";
            /** Format: date-time */
            expectStartAt?: string;
            /** Format: date-time */
            expectEndAt?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
        };
        SliceSessionResponseDto: {
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["SessionResponseDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            empty?: boolean;
        };
        SortObject: {
            unsorted?: boolean;
            sorted?: boolean;
            empty?: boolean;
        };
        RsDataSessionResponseDto: {
            success?: boolean;
            data?: components["schemas"]["SessionResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        AttendanceDto: {
            /** Format: int64 */
            recordId?: number;
            /** Format: int64 */
            memberId?: number;
            memberName?: string;
            stdId?: string;
            /** @enum {string} */
            attendanceStatus?: "PRESENT" | "ABSENT" | "ETC" | "LATE";
            /** Format: date-time */
            checkedAt?: string;
            isManual?: boolean;
            adminNote?: string;
        };
        RsDataSliceAttendanceDto: {
            success?: boolean;
            data?: components["schemas"]["SliceAttendanceDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        SliceAttendanceDto: {
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AttendanceDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            empty?: boolean;
        };
        ClubMemberResponse: {
            /** Format: int64 */
            memberId?: number;
            name?: string;
            stdId?: string;
            /** @enum {string} */
            role?: "ADMIN" | "MEMBER";
            /** Format: double */
            rate?: number;
        };
        RsDataListClubMemberResponse: {
            success?: boolean;
            data?: components["schemas"]["ClubMemberResponse"][];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        AttendanceRecordItem: {
            /** Format: int64 */
            sessionId?: number;
            sessionName?: string;
            /** Format: date */
            date?: string;
            /** @enum {string} */
            status?: "PRESENT" | "ABSENT" | "ETC" | "LATE";
            /** Format: date-time */
            checkedAt?: string;
            adminNote?: string;
        };
        MyAttendanceRecordDto: {
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            month?: number;
            records?: components["schemas"]["AttendanceRecordItem"][];
            status?: components["schemas"]["StatusSummary"];
            /** Format: double */
            attendanceRate?: number;
        };
        RsDataMyAttendanceRecordDto: {
            success?: boolean;
            data?: components["schemas"]["MyAttendanceRecordDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
        StatusSummary: {
            /** Format: int64 */
            present?: number;
            /** Format: int64 */
            absent?: number;
            /** Format: int64 */
            late?: number;
            /** Format: int64 */
            etc?: number;
        };
        ExportItem: {
            memberName?: string;
            stdId?: string;
            sessionName?: string;
            /** Format: date */
            date?: string;
            /** @enum {string} */
            status?: "PRESENT" | "ABSENT" | "ETC" | "LATE";
            adminNote?: string;
        };
        ExportResponseDto: {
            data?: components["schemas"]["ExportItem"][];
        };
        RsDataExportResponseDto: {
            success?: boolean;
            data?: components["schemas"]["ExportResponseDto"];
            error?: components["schemas"]["ErrorInfo"];
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSessions: {
        parameters: {
            query?: {
                status?: "SCHEDULED" | "ACTIVE" | "ENDED";
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 세션 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataSliceSessionResponseDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 해당 동아리의 멤버가 아닌 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequestDto"];
            };
        };
        responses: {
            /** @description 세션 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 또는 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 세션 시작 성공 (OTP 코드 반환) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataSessionStartDto"];
                };
            };
            /** @description OTP 코드 생성 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "OTP_GENERATION_FAILED",
                     *         "message": "출석 코드 생성에 실패했습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_NOT_FOUND",
                     *         "message": "해당 세션이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 이미 진행 중이거나 종료된 세션인 경우 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_ALREADY_ACTIVE",
                     *         "message": "이미 진행 중인 세션이 있습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    endedSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 세션 종료 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataString"];
                };
            };
            /** @description 활성화된 세션이 아닌 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_NOT_ACTIVE",
                     *         "message": "현재 활성화된 세션이 없습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_NOT_FOUND",
                     *         "message": "해당 세션이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getSessionAttendance: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 출석 현황 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataSliceAttendanceDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_NOT_FOUND",
                     *         "message": "해당 세션이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    checkAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceCheckRequestDto"];
            };
        };
        responses: {
            /** @description 출석 처리 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataString"];
                };
            };
            /** @description 세션이 활성화 상태가 아니거나 OTP 코드가 올바르지 않은 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 해당 동아리의 멤버가 아닌 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션 또는 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 이미 출석 처리된 경우 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "ALREADY_CHECKED_IN",
                     *         "message": "이미 출석 처리된 세션입니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    manualCheckAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAttendanceRequestDto"];
            };
        };
        responses: {
            /** @description 수동 출석 처리 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataString"];
                };
            };
            /** @description ABSENT 상태로 수동 처리 시도 또는 세션이 활성화 상태가 아닌 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션 또는 대상 멤버가 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 대상 멤버가 이미 출석 처리된 경우 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "ALREADY_CHECKED_IN",
                     *         "message": "이미 출석 처리된 세션입니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getCurrentInviteCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초대코드 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataInviteResponseDto"];
                };
            };
            /** @description 유효한 초대코드가 없는 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "INVALID_INVITE_CODE",
                     *         "message": "초대코드가 존재하지 않거나 유효하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리가 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "CLUB_NOT_FOUND",
                     *         "message": "동아리가 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    issueInviteCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초대코드 발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataInviteResponseDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 또는 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    revokeInviteCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초대코드 무효화 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description 유효한 초대코드가 없는 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "INVALID_INVITE_CODE",
                     *         "message": "초대코드가 존재하지 않거나 유효하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리가 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "CLUB_NOT_FOUND",
                     *         "message": "동아리가 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    joinClub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequestDto"];
            };
        };
        responses: {
            /** @description 동아리 가입 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description 초대코드가 유효하지 않거나 무효화된 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "INVALID_INVITE_CODE",
                     *         "message": "초대코드가 존재하지 않거나 유효하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 또는 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 이미 해당 동아리의 멤버인 경우 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "ALREADY_CLUB_MEMBER",
                     *         "message": "이미 해당 동아리의 멤버입니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    createClub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClubDto"];
            };
        };
        responses: {
            /** @description 동아리 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataClubCreateResponseDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "MEMBER_NOT_FOUND",
                     *         "message": "해당 회원이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 회원가입 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataSignupResponse"];
                };
            };
            /** @description 유효성 검증 실패 (학번 8자리 아님 / 비밀번호 형식 오류 / 필수값 누락) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "VALIDATION_FAILED",
                     *         "message": "비밀번호는 영어와 숫자를 각각 1개 이상 포함해야 합니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 이미 사용중인 학번 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "DUPLICATE_STUDENT_ID",
                     *         "message": "이미 사용중인 학번입니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReissueTokenRequest"];
            };
        };
        responses: {
            /** @description 토큰 재발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataTokenResponse"];
                };
            };
            /** @description 토큰 만료 / 형식 오류 / 이미 무효화된 Refresh Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 토큰에 담긴 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "MEMBER_NOT_FOUND",
                     *         "message": "해당 회원이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "MEMBER_NOT_FOUND",
                     *         "message": "해당 회원이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataTokenResponse"];
                };
            };
            /** @description 학번 없음 또는 비밀번호 불일치 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "INVALID_CREDENTIALS",
                     *         "message": "학번 또는 비밀번호가 올바르지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 내 정보 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMemberProfileResponse"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "MEMBER_NOT_FOUND",
                     *         "message": "해당 회원이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    updateMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description 내 정보 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMemberProfileResponse"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "MEMBER_NOT_FOUND",
                     *         "message": "해당 회원이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    updateMyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberPaswordUpdateRequest"];
            };
        };
        responses: {
            /** @description 비밀번호 변경 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "MEMBER_NOT_FOUND",
                     *         "message": "해당 회원이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    updateFcmToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FcmTokenUpdateRequest"];
            };
        };
        responses: {
            /** @description FCM 토큰 갱신 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "MEMBER_NOT_FOUND",
                     *         "message": "해당 회원이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getClub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 동아리 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataClubResponseDto"];
                };
            };
            /** @description 이미 삭제된 동아리인 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "CLUB_ALREADY_DELETED",
                     *         "message": "삭제된 동아리입니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리가 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "CLUB_NOT_FOUND",
                     *         "message": "동아리가 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    updateClub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClubDto"];
            };
        };
        responses: {
            /** @description 동아리 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataString"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리가 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "CLUB_NOT_FOUND",
                     *         "message": "동아리가 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 세션 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataSessionResponseDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 해당 동아리의 멤버가 아닌 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_NOT_FOUND",
                     *         "message": "해당 세션이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    softDeletedSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 세션 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataString"];
                };
            };
            /** @description 진행 중인 세션은 삭제 불가 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "NOT_DELETED_SESSION",
                     *         "message": "활동중이라 삭제할 수 없는 세션입니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_NOT_FOUND",
                     *         "message": "해당 세션이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    updatedSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionDto"];
            };
        };
        responses: {
            /** @description 세션 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataString"];
                };
            };
            /** @description 이미 종료된 세션인 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_ALREADY_ENDED",
                     *         "message": "종료된 세션은 수정할 수 없습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_NOT_FOUND",
                     *         "message": "해당 세션이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                sessionId: number;
                recordId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceStatusUpdateDto"];
            };
        };
        responses: {
            /** @description 출석 상태 변경 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataString"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 출석 기록이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "ATTENDANCE_NOT_FOUND",
                     *         "message": "출석 기록이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdateRequest"];
            };
        };
        responses: {
            /** @description 역할 변경 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 회원이 존재하지 않거나 대상이 동아리 멤버가 아닌 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    softDeleteClub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 동아리 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataString"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리가 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "CLUB_NOT_FOUND",
                     *         "message": "동아리가 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getTrend: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
            };
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 출석 트렌드 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataTrendResponseDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getMemberStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버별 출석률 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMemberStatsResponseDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getDistribution: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
            };
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 출석 분포 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataDistributionResponseDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getActiveSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 활성 세션 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataSessionResponseDto"];
                };
            };
            /** @description 현재 활성화된 세션이 없는 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "SESSION_NOT_ACTIVE",
                     *         "message": "현재 활성화된 세션이 없습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 해당 동아리의 멤버가 아닌 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getClubMembers: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListClubMemberResponse"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 회원이 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "MEMBER_NOT_FOUND",
                     *         "message": "해당 회원이 존재하지 않습니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getMyRecords: {
        parameters: {
            query?: {
                year?: number;
                month?: number;
            };
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 내 출석 기록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMyAttendanceRecordDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 해당 동아리의 멤버가 아닌 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getExportData: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
                memberId?: number;
            };
            header?: never;
            path: {
                clubId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 출석 데이터 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataExportResponseDto"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    softdeletedMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: number;
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 제명 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Access Token 만료 또는 형식 오류 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 동아리 멤버가 아니거나 ADMIN 권한이 없는 경우 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 대상 멤버가 동아리에 존재하지 않는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "data": null,
                     *       "error": {
                     *         "code": "NOT_CLUB_MEMBER",
                     *         "message": "해당 동아리의 멤버가 아닙니다."
                     *       },
                     *       "timestamp": "2025-04-25T10:00:00"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
}
